// src/components/NavigationMenu/NavigationMenu.tsx
import styles from './NavigationMenu.module.css';

export default function NavigationMenu() {
  return (
    <div id="navigation-wrapper" className={styles.wrapper}>
      <nav className={styles.menu}>
        <ul className={styles.items}>
          <li className={styles.item}>
            <a href="#navigation-wrapper">Home</a>
          </li>
          <li className={styles.item}>
            <a href="#about-me-wrapper">About</a>
          </li>
          <li className={styles.item}>
            <a href="#projects-wrapper">Projects</a>
          </li>
          <li className={styles.item}>
            <a href="#footer-links-wrapper">Contact</a>
          </li>
        </ul>
        <div className={styles.menuItem}>
          <a href="#">Profile</a>
        </div>
      </nav>
    </div>
  );
}

// src/app/components/navigation-menu/navigation-menu.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-navigation-menu',
    templateUrl: './navigation-menu.component.html',
    styleUrls: ['./navigation-menu.component.css']
})
export class NavigationMenuComponent implements OnInit {

    constructor() {
    }

    ngOnInit() {
    }
}

<div id="navigation-wrapper">
    <div class="navigation-menu">
        <ul class="navigation-items">
            <li class="navigation-item"><a href="#navigation-wrapper"> Home </a></li>
            <li class="navigation-item"><a href="#about-me-wrapper"> About </a></li>
            <li class="navigation-item"><a href="#links-wrapper"> Projects </a></li>
            <li class="navigation-item"><a href="#footer-links-wrapper"> Contact </a></li>
        </ul>
        <!-- Hidden until window is smaller than 600 pixels -->
        <li class="navigation-item menu-item"><a href="#"> Menu </a></li>
    </div>
</div>
